---
- yum:
    name: "*"
    state: latest
    update_cache: yes
- yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - unzip
    - zip
    - python-pip
    - libunwind
    - libicu


